---
# EXAMPLE USAGE:
#
#   Refer for explanation to following link:
#   https://lefthook.dev/configuration/

pre-commit:
  parallel: true
  jobs:
    - name: bandit
      glob: "{*.py,*.pyi}"
      run: bandit -c pyproject.toml {staged_files}

    - name: pyright
      glob: "{*.py,*.pyi}"
      run: pyright {staged_files}

    - name: taplo-format-pyproject
      glob: "{pyproject.toml}"
      run: taplo format pyproject.toml

    - name: uv-lock
      glob: "{pyproject.toml,uv.lock}"
      group:
        piped: true
        jobs:
          - run: uv lock
          - run: git add uv.lock

pre-push:
  jobs:
    - name: pyright
      glob: "{*.py,*.pyi}"
      run: pyright .

    - name: uv-lock-frozen
      glob: "{pyproject.toml,uv.lock}"
      group:
        piped: true
        jobs:
          - run: uv lock --frozen
          - run: git add uv.lock
