---
# EXAMPLE USAGE:
#
#   Refer for explanation to following link:
#   https://lefthook.dev/configuration/

pre-commit:
  parallel: true
  jobs:
    - name: markdownlint
      glob: "{*.md,*.mdown,*.markdown}"
      run: docker run -v $PWD:/workdir davidanson/markdownlint-cli2:v0.18.1 {staged_files}
