[project]
name = "python-template"
version = "0.1.0"
description = "Python template"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = ["lefthook==1.11.13"]
